redirect:
  path: /
  controller: App\Controller\RedirectController::redirectToTwitter

callback:
  path: /callback
  controller: App\Controller\CallbackController::callbackFromTwitter
  methods: GET

clear:
  path: /clear
  controller: App\Controller\ClearSessionController::clear
  methods: GET
