redirect:
  path: /
  controller: App\Controller\RedirectController::redirectToTwitter

callback:
  path: /callback
  controller: App\Controller\CallbackController::callbackFromTwitter
  methods: GET

clear:
  path: /clear
  controller: App\Controller\ClearSessionController::clear
  methods: GET

connection_error:
  path: /connection_error
  controller: App\Controller\ConnectionErrorController::error
  methods: GET

verify:
  path: /verify
  controller: App\Controller\VerifyCredentialsController::verify
  methods: GET
