services:
  Application\Service\TwitterOAuthFactory:
    arguments:
      $consumerKey: '%env(CONSUMER_KEY)%'
      $consumerSecret: '%env(CONSUMER_SECRET)%'
      $session: '@session'

  Abraham\TwitterOAuth\TwitterOAuth:
    factory: ['@Application\Service\TwitterOAuthFactory', 'create']

  Application\Service\TwitterService:
    arguments:
      - '@Abraham\TwitterOAuth\TwitterOAuth'
      - '%env(OAUTH_CALLBACK)%'
      - '@session'
